name=Boardoza DRV2605L Haptic Driver
version=1.0.0
author=Boardoza <eray.eroglu@boardoza.com>
maintainer=Boardoza <Boardoza.com>
sentence=Library for Boardoza DRV2605L Haptic Driver
paragraph=This library provides an easy-to-use API for interfacing with the DRV2605L haptic driver. It supports configuration, waveform playback, and advanced features for vibration motors. Designed for Arduino and PlatformIO projects, it includes example sketches and minimal dependencies.
category=Motor Control
url=https://github.com/Boardoza/Boardoza_DRV2605L_Haptic_Driver_Breakout_Board
architectures=*